Relax detection of compilation errors
This is used to retry without build isolation, but the message has
changed in recent pip versions and was no longer matched. Now, at least
in some cases, the error reads like this:

```
pip._internal.exceptions.InstallationSubprocessError: Getting requirements to build wheel exited with 1
```